//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTTIENNGHI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTTIENNGHI()
        {
            this.Phong_CTTIENNGHI = new HashSet<Phong_CTTIENNGHI>();
        }
    
        public string MACTTN { get; set; }
        public string TENTIENNGHI { get; set; }
        public string MATIENNGHI { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        public virtual TIENNGHI TIENNGHI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phong_CTTIENNGHI> Phong_CTTIENNGHI { get; set; }
    }
}
