//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICHVUPHONG
    {
        public string MAPHONG { get; set; }
        public string MADV { get; set; }
        public Nullable<double> TRIGIADV { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
