//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICHVU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DICHVU()
        {
            this.DICHVUPHONGs = new HashSet<DICHVUPHONG>();
        }
    
        public string MADV { get; set; }
        public string TENDV { get; set; }
        public string MALOAIDV { get; set; }
        public Nullable<double> TRIGIADV { get; set; }
    
        public virtual LOAIDICHVU LOAIDICHVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DICHVUPHONG> DICHVUPHONGs { get; set; }
    }
}
