//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.HOADONs = new HashSet<HOADON>();
            this.PHIEUDATPHONGs = new HashSet<PHIEUDATPHONG>();
        }
    
        public string MANV { get; set; }
        public string HOVATEN { get; set; }
        public System.DateTime NGAYVAOLAM { get; set; }
        public System.DateTime NGAYSINH { get; set; }
        public string CHUCVU { get; set; }
        public string GIOITINH { get; set; }
        public string CCCD { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public Nullable<double> LUONG { get; set; }
        public Nullable<int> MATK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDATPHONG> PHIEUDATPHONGs { get; set; }
    }
}
