//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong_CTTIENNGHI
    {
        public string MAPHONG { get; set; }
        public string MACTTN { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        public virtual CTTIENNGHI CTTIENNGHI { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
